spring.application.name=menu
spring.datasource.url=jdbc:postgresql://localhost:5432/menudb
spring.datasource.username=postgres
spring.datasource.password=Pe7bq7nC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
