spring.application.name=menu
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB:menudb}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
